kind: ConfigMap
apiVersion: v1
metadata:
  name: proxy-configmap
data: 
  my_server_block.conf: |-
    server {
      listen 8080;
      ssi on;

      location /healthz {
        return 200 'woop woop!';
        add_header Content-Type text/plain;
      }

      location /l/ {
        proxy_pass  https://kwik-e-mart-v3-appshell-list.apps.baloise.dev;
      }
      location /d/ {
        proxy_pass  https://kwik-e-mart-v3-appshell-detail.apps.baloise.dev;
      }
      location /c/ {
        proxy_pass  https://kwik-e-mart-v3-appshell-checkout.apps.baloise.dev;
      }
      location / {
        root /opt/html;
        try_files $uri $uri/ /index.html;
      }
    }