frontend:
  image:
    repository: balcodecampmicrofrontend/kwik-e-list
    tag: 88910e81722fe2c70c44ff2bc88efa6d55a7c74d
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: kwik-e-list.apps.baloise.dev
  readinessProbe:
    httpGet:
      path: /healthz
      port: 8080
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8080
