frontend:
  image:
    repository: balcodecampmicrofrontend/kwik-e-checkout
    tag: 71418393b3c3fcd4a27caf18cc29bc16fbc3c0da
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: kwik-e-checkout.apps.baloise.dev
