frontend:
  image:
    repository: balcodecampmicrofrontend/kwik-e-checkout
    tag: 6e4d13c9a6bbc2ca56d011193679eed6be3cfe01
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: kwik-e-checkout.apps.baloise.dev
