frontend:
  image:
    repository: balcodecampmicrofrontend/kwik-e-checkout
    tag: c44106044820634ca939f4541a587f184899caad
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: kwik-e-checkout.apps.baloise.dev
