frontend:
  image:
    repository: balcodecampmicrofrontend/kwik-e-checkout
    tag: 882b7a85b8219d72596ee237a7a5f529ca39dd57
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: kwik-e-checkout.apps.baloise.dev
