frontend:
  image:
    repository: balcodecampmicrofrontend/kwik-e-checkout
    tag: 06a5ac7fb5854622e56ba31ca699fc92e89a6882
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: kwik-e-checkout.apps.baloise.dev
