frontend:
  image:
    repository: balcodecampmicrofrontend/kwik-e-checkout
    tag: 684923fe6b0b8d4c2226998f3caeb99e2cece667
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: kwik-e-checkout.apps.baloise.dev
