frontend:
  image:
    repository: balcodecampmicrofrontend/kwik-e-checkout
    tag: f6f353a72b3b345733de0060b0ffb4d58c1aac28
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: kwik-e-checkout.apps.baloise.dev
