frontend:
  image:
    repository: balcodecampmicrofrontend/kwik-e-checkout
    tag: 8e0322e0d98e34a8a1b39bff9bccc840a6a973c3
  replicaCount: 1
  network:
    http:
      servicePort: 3002
      ingress:
        host: kwik-e-checkout.apps.baloise.dev
  readinessProbe:
    httpGet:
      path: /healthz
      port: http
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
