frontend:
  image:
    repository: balcodecampmicrofrontend/kwik-e-checkout
    tag: 44215f135d6212942d32c121244c38beccf2447f
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: kwik-e-checkout.apps.baloise.dev
