frontend:
  image:
    repository: balcodecampmicrofrontend/kwik-e-checkout
    tag: a0aca59e7582c40184ffd9a6128ec20fb72fa5c4
  replicaCount: 1
  network:
    http:
      servicePort: 3002
      ingress:
        host: kwik-e-checkout.apps.baloise.dev
  readinessProbe:
    httpGet:
      path: /healthz
      port: http
  livenessProbe:
    httpGet:
      path: /healthz
      port: http