frontend:
  image:
    repository: balcodecampmicrofrontend/kwik-e-checkout
    tag: 4c0fd35c2d8bd9670c5ee334575cd71b284b0bcd
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: kwik-e-checkout.apps.baloise.dev
