frontend:
  image:
    repository: balcodecampmicrofrontend/kwik-e-checkout
    tag: cd14a767a7ff7e4cc4a8d1cdc41ec2182be7d6e3
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: kwik-e-checkout.apps.baloise.dev
