frontend:
  image:
    repository: balcodecampmicrofrontend/kwik-e-checkout
    tag: a660ac728bbe4894f9e3a5ba0cd12f64a03a4e9e
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: kwik-e-checkout.apps.baloise.dev
