frontend:
  image:
    repository: balcodecampmicrofrontend/kwik-e-checkout
    tag: 7d051f7eee99c77a9b25371cad7c00d595ea57f7
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: kwik-e-checkout.apps.baloise.dev
