frontend:
  image:
    repository: balcodecampmicrofrontend/kwik-e-checkout
    tag: 23daa1185c6e9d054f4142445ddf937ff22ef8b0
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: kwik-e-checkout.apps.baloise.dev
