frontend:
  image:
    repository: balcodecampmicrofrontend/kwik-e-checkout
    tag: 091e366e2461e58f5007a873adc9d77369ce1ce3
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: kwik-e-checkout.apps.baloise.dev
