frontend:
  image:
    repository: balcodecampmicrofrontend/kwik-e-checkout
    tag: 3c7023c2ec0987c423119b2f4f87d9aabae5cecc
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: kwik-e-checkout.apps.baloise.dev
