frontend:
  image:
    repository: balcodecampmicrofrontend/kwik-e-checkout
    tag: cf5fba74a925f587338ee0418b1732cea875a0e8
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: kwik-e-checkout.apps.baloise.dev
