frontend:
  image:
    repository: balcodecampmicrofrontend/kwik-e-checkout
    tag: 3c50930f3a4f38253a221676fe7d2174b552b00d
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: kwik-e-checkout.apps.baloise.dev
