frontend:
  image:
    repository: balcodecampmicrofrontend/kwik-e-checkout
    tag: dc93884cd025b91e06e22c5f088ca8384b2ecf19
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: kwik-e-checkout.apps.baloise.dev
