frontend:
  image:
    repository: balcodecampmicrofrontend/kwik-e-checkout
    tag: b867966f98652dff8ffa37305588b78f03b94ad9
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: kwik-e-checkout.apps.baloise.dev
