frontend:
  image:
    repository: balcodecampmicrofrontend/kwik-e-checkout
    tag: 7c4fe034a0a55f805d55c0b029c29c6eb9184be7
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: kwik-e-checkout.apps.baloise.dev
