frontend:
  image:
    repository: balcodecampmicrofrontend/kwik-e-checkout
    tag: be33278f2d3b75ed6e55457e20a99e70002d9dc4
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: kwik-e-checkout.apps.baloise.dev
