frontend:
  image:
    repository: balcodecampmicrofrontend/kwik-e-checkout
    tag: 34dab9047f530ffea5bc487104efcf0b270e8d1a
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: kwik-e-checkout.apps.baloise.dev
