frontend:
  image:
    repository: balcodecampmicrofrontend/kwik-e-checkout
    tag: ef1908e8addb7d711cd78d369ea7b7b1001d37a3
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: kwik-e-checkout.apps.baloise.dev
