frontend:
  image:
    repository: balcodecampmicrofrontend/kwik-e-checkout
    tag: 8ee5a2a3ef4a30591caa17690d18e96fc93fc63c
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: kwik-e-checkout.apps.baloise.dev
