frontend:
  image:
    repository: balcodecampmicrofrontend/kwik-e-checkout
    tag: 5fa64a541f12d0c2b53bf2d59dbff4838ae1fd7f
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: kwik-e-checkout.apps.baloise.dev
