frontend:
  image:
    repository: balcodecampmicrofrontend/frontend-alpha
    tag: 9172198617660c1f203c05cc7528ee0571e1f670
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: frontend-alpha-micro-frontends-test.apps.baloise.dev
