api:
  image:
    repository: balcodecampmicrofrontend/kwik-e-api
    tag: 4b030132c3bee5068995b22092199876fd51401d
  replicaCount: 1
  network:
    http:
      servicePort: 3003
      ingress:
        host: kwik-e-api.apps.baloise.dev
  readinessProbe:
    httpGet:
      path: /healthz
      port: http
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
