kwik-e-proxy:
  image:
    repository: balcodecampmicrofrontend/kwik-e-proxy
    tag: b0e51e9f747762da8806e9c78062da1052f8b742
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: kwik-e-mart-v3-appshell-proxy.apps.baloise.dev
  readinessProbe:
    httpGet:
      path: /healthz
      port: 8080
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8080
  volumeMounts:
    - name: proxy-configmap-volume
      mountPath: /opt/bitnami/nginx/conf/server_blocks
  volumes:
    - name: proxy-configmap-volume
      configMap:
        name: proxy-configmap

kwik-e-list:
  image:
    repository: balcodecampmicrofrontend/kwik-e-list
    tag: cabbd76acd7a3e14e614bcdfff292b7405d1d710
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: kwik-e-mart-v3-appshell-list.apps.baloise.dev
  readinessProbe:
    httpGet:
      path: /healthz
      port: 8080
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8080

kwik-e-detail:
  image:
    repository: balcodecampmicrofrontend/kwik-e-detail
    tag: 8e7febe66850ff9991981482c978c8e92f101157
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: kwik-e-mart-v3-appshell-detail.apps.baloise.dev
  readinessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8080

kwik-e-checkout:
  image:
    repository: balcodecampmicrofrontend/kwik-e-checkout
    tag: 6e4d13c9a6bbc2ca56d011193679eed6be3cfe01
  replicaCount: 1
  network:
    http:
      servicePort: 8080
      ingress:
        host: kwik-e-mart-v3-appshell-checkout.apps.baloise.dev

